# This is a reusable workflow used by infra to prevent scheduled deployments from happening on bank holidays
name: Bank Holiday Check

on:
  workflow_call:

jobs:
  check-bank-holiday:
    runs-on: ubuntu-latest
    outputs:
      is_bank_holiday: ${{ steps.check.outputs.is_bank_holiday }}
    steps:
      - name: Check if today is a bank holiday
        id: check
        run: |
          echo "is_bank_holiday=true" >> "$GITHUB_OUTPUT"
