# Implicitly requires the IAM_GITHUB_ROLE_ARN secret to be set for the dev2 environment

name: Build image and deploy to dev2 on merge to main

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The locally built image name, e.g., eip-ero-applications-api
      ecr_repo:
        required: true
        type: string
        description: The ECR repository name, e.g., applications-api-repo
      app_name_dev2_prefix:
        required: true
        type: string
        description: The app name with the dev2 environment prepended, e.g., dev2-applications-api

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.find-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6

      - name: Get latest patch version tag for major version
        id: find-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          prefix: 'v2.'

  bump-and-push-tag:
    needs: get-latest-tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/bump-and-push-tag.yml@main
    with:
      version: ${{ needs.get-latest-tag.outputs.version }}
      bump_level: minor

  build-and-push:
    needs: bump-and-push-tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/build-and-push.yml@main
    with:
      version: ${{ needs.bump-and-push-tag.outputs.version }}
      image_name: ${{ inputs.image_name }}
      ecr_repo: ${{ inputs.ecr_repo }}
      preprod_deploy_environment: dev2
    secrets: inherit

  deploy:
    needs:
      - bump-and-push-tag
      - build-and-push
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/deploy.yml@main
    with:
      deploy_environment: dev2
      version: ${{ needs.bump-and-push-tag.outputs.version }}
      app_name_with_env: ${{ inputs.app_name_dev2_prefix }}
      ecr_repo: ${{ inputs.ecr_repo }}
    secrets: inherit
