name: Get latest, bump minor, and push version tag

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      bump_level:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Bump version tag
        id: bump-semver
        # Note the `v` prefix before the output of npx.
        # semver accepts input with a `v` prefix, but does not output the version with one.
        run: |
          npm install -g npm@11 --fund=false --audit=false
          echo "new_version=v$(npx -y semver@7 ${{ inputs.version }} -i ${{ inputs.bump_level }})" >> $GITHUB_OUTPUT

      - name: Push version tag
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "${tag}"
          git push origin "${tag}"
