# Implicitly requires the IAM_GITHUB_ROLE_ARN secret to be set for the dev2 environment

name: "Hotfix: Build, tag, and push hotfix image"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The locally built image name, e.g., eip-ero-applications-api
      ecr_repo:
        required: true
        type: string
        description: The ECR repository name, e.g., applications-api-repo

jobs:
  check-untagged:
    runs-on: ubuntu-latest
    outputs:
      untagged: ${{ !startsWith(env.MATCHING_TAGS, 'v') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check untagged (don't run for branch creation)
        id: get-matching-tags
        shell: bash
        run: |
          MATCHING_TAGS=$(git tag --contains HEAD)
          echo "Matching tags: $MATCHING_TAGS"
          echo "MATCHING_TAGS=$MATCHING_TAGS" >> $GITHUB_ENV

  tag:
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/tag.yml@main

  build-and-push:
    needs: tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/build-and-push.yml@main
    with:
      version: ${{ needs.tag.outputs.version }}
      image_name: ${{ inputs.image_name }}
      ecr_repo: ${{ inputs.ecr_repo }}
      preprod_deploy_environment: dev2
    secrets: inherit
