# Implicitly requires the IAM_GITHUB_ROLE_ARN secret to be set for the dev2 environment

name: "Hotfix: Build, tag, and push hotfix image"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The locally built image name, e.g., eip-ero-applications-api
      ecr_repo:
        required: true
        type: string
        description: The ECR repository name, e.g., applications-api-repo

jobs:
  check-untagged:
    runs-on: ubuntu-latest
    outputs:
      untagged: ${{ !startsWith(env.MATCHING_TAGS, 'v') }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check untagged (don't run for branch creation)
        id: get-matching-tags
        shell: bash
        run: |
          MATCHING_TAGS=$(git tag --contains HEAD)
          echo "Matching tags: $MATCHING_TAGS"
          echo "MATCHING_TAGS=$MATCHING_TAGS" >> $GITHUB_ENV

  get-latest-tag:
    runs-on: ubuntu-latest
    needs: check-untagged
    if: needs.check-untagged.outputs.untagged == 'true'
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v5

      - name: Get minor version of branch
        shell: bash
        run: |
          echo "${{ needs.check-untagged.outputs.untagged }}"
          BRANCH_VERSION=${GITHUB_REF#refs/*/hotfix/}
          BRANCH_VERSION=${BRANCH_VERSION%.*}
          echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV

      - name: Get latest patch version tag for minor version
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          releases-only: false
          prefix: '${{ env.BRANCH_VERSION }}'

  bump-and-push-tag:
    needs: get-latest-tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/bump-and-push-tag.yml@main
    with:
      version: ${{ needs.get-latest-tag.outputs.version }}
      bump_level: patch

  build-and-push:
    needs: bump-and-push-tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/build-and-push.yml@main
    with:
      version: ${{ needs.bump-and-push-tag.outputs.version }}
      image_name: ${{ inputs.image_name }}
      ecr_repo: ${{ inputs.ecr_repo }}
      preprod_deploy_environment: dev2
    secrets: inherit
